"""Austando nome do Model, route_acess_log - user_agent_plafform to user_agent_platform

Revision ID: 27ba5383f16b
Revises: c96e24745a07
Create Date: 2025-12-06 14:47:46.713029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ba5383f16b'
down_revision: Union[str, Sequence[str], None] = 'c96e24745a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_access_log', sa.Column('user_agent_platform', sa.String(length=100), nullable=True))
    op.drop_column('route_access_log', 'user_agent_plafform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_access_log', sa.Column('user_agent_plafform', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('route_access_log', 'user_agent_platform')
    # ### end Alembic commands ###
