"""Austando tabela user access

Revision ID: 42f09ea4d42b
Revises: 8e953180aff9
Create Date: 2025-12-06 10:46:17.254647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42f09ea4d42b'
down_revision: Union[str, Sequence[str], None] = '8e953180aff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapper_books')
    op.drop_column('user_access', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_table('scrapper_books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('availability', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('upc', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('product_type', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('price_excl_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_incl_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('number_of_reviews', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scrapper_books_pkey'))
    )
    # ### end Alembic commands ###
