"""Adicionando model book_recommendations

Revision ID: 6292681dfe0b
Revises: 18a6023efa93
Create Date: 2025-12-18 02:34:31.140084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6292681dfe0b'
down_revision: Union[str, Sequence[str], None] = '18a6023efa93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_book_id', sa.Integer(), nullable=True),
    sa.Column('original_title', sa.String(length=500), nullable=False),
    sa.Column('recommended_book_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_recommendation')
    # ### end Alembic commands ###
