"""Criando tabela de log das rotas

Revision ID: c96e24745a07
Revises: 42f09ea4d42b
Create Date: 2025-12-06 14:37:27.932553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96e24745a07'
down_revision: Union[str, Sequence[str], None] = '42f09ea4d42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=300), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=150), nullable=True),
    sa.Column('route_blueprint', sa.String(length=150), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('user_agent_browser', sa.String(length=300), nullable=True),
    sa.Column('user_agent_plafform', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_access_log')
    # ### end Alembic commands ###
